include: [".well-known"]

title: James Alfei
author:
  name: James Alfei
  email: jamesalfei@icloud.com
google_analytics: UA-42788533-1
tagline: The personal website of James Alfei
url: "https://jamesalfei.co.uk"
description: >
  The personal website of James Alfei.

# Build settings
compress-site: yes
plugins:
  - jekyll-feed

remote_theme: jamesalfei/minima

minima-jamesalfei:
  skin: dark
  social_links:
    github:  jamesalfei
    linkedin: jamesalfei
    keybase: jamesalfei

# Navigation pages
header_pages:
  - pages/online-cv.md
  - pages/portfolio.md

# SEO Plugin properties
social:
  name: James Alfei
  links:
    - https://www.linkedin.com/in/jamesalfei
    - https://github.com/jamesalfei

theme: jekyll-theme-minimal