include: [".well-known"]

title: James Alfei
author:
  name: James Alfei
  email: james@alfei.uk
google_analytics: UA-42788533-1
tagline: Software Engineer
url: "https://jamesalfei.co.uk"
description: >
  James Alfei - Software Engineer

# Build settings
compress-site: yes

remote_theme: jekyll/minima

minima:
  skin: auto
  social_links:
    - { platform: github, user_url: "https://github.com/jamesalfei" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jamesalfei" }

# Navigation pages
#header_pages:
#  - pages/online-cv.md

# SEO Plugin properties
social:
  name: James Alfei
  links:
    - https://www.linkedin.com/in/jamesalfei
    - https://github.com/jamesalfei
