name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build site:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Build the site
      run: |
        set -e

        echo "Building site..."

        bundle exec jekyll build

        if test -e "./_site/index.html";then
          echo "Site built successfully."
          rm -Rf _site
        else
          echo "Site build unsuccessful."
          exit 1
        fi
      shell: bash
